import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/app/styles/globals.css";
import CommonHeader from "@/components/common/header/CommonHeader";
import { Toaster } from "sonner";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Event Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CommonHeader />
      <html lang="en">
        <body className={roboto.className}>{children}</body>
        <Toaster />
      </html>
    </>
  );
}
