import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/styles/globals.css";
import CommonHeader from "@/components/common/header/CommonHeader";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Event Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <CommonHeader />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
