import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/app/styles/globals.css";
import { Toaster } from "sonner";
import SideNavigation from "@/components/common/navigation/SideNavigation";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Event Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex">
          <SideNavigation />
          <main>{children}</main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
