import type { Metadata } from "next";
import "@/app/styles/globals.css";
import { Toaster } from "sonner";
import SideNavigation from "@/components/common/navigation/SideNavigation";

export const metadata: Metadata = {
  title: "Event Platform",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col sm:flex-row">
      <SideNavigation />
      <main>{children}</main>
      <Toaster />
    </div>
  );
}
